### ISSUE TITLE
Data preparation for relative pose not working

### ISSUE THREAD

**Issue by BornInWater** [ensv/RPNet#2]
Hi,
I ran python3 absolute_cambridge.py  and that worked and downloaded all the data. 
For, python3 relative_cambridge.py, it gives the following error:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/mnt/Work/RPNet/log_dir//relative_cambridge/KingsCollege/dataset_train.txt'
So, just for trying , I copied KingsCollege folder from the absolute_cambridge directory in log_dir to relative_cambridge and then ran the relative_cambridge.py code. This skipped KingsCollege folder as the tf records already exist and then gave similar error as above for OldHospital directory. 

So, are new files supposed to be explicitly generated for this or the same data in absolute_cambridge suffices?

**Comment by ensv** [comment]
Because we want to compare the results between relative and absolute pose, so the train test split must be the same. One simple trick you could do is to make a copy of your "absolute_cambridge" and named it as "relative_cambridge" then delete all your tfrecord file in "relative_cambridge" to let the program prepare all the data again.

**Comment by BornInWater** [comment]
Thanks!

**Comment by russellyq** [comment]
Hi ! Thanks for your code.
I met the same problem as @BornInWater  and did what @ensv told.
However, errors occur when loading the images:

------------------------------------------------------------
"""
Traceback (most recent call last):
  File "/home/robot/anaconda3/envs/py36/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/robot/anaconda3/envs/py36/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "relative_cambridge.py", line 55, in _read_image
    im2 = cv2.imread(each[8])  # @UndefinedVariable
IndexError: index 8 is out of bounds for axis 0 with size 8
"""
---------------------------------------------------------
I am confused how you load the images in this 'multiprocessing' way.

Thank you in advance !
